### PR TITLE
Better Google Maps search box

### PR DESCRIPTION
**Pull request by Wowu**
* Update the box to match new Google Maps design:

| Before | After |
| --- | --- |
| screen shot 2018-10-27 at 18 01 03 | screen shot 2018-10-27 at 18 05 41 |

* Don't send ActiveAdmin form after hitting enter in the search box.

---

⚠️ This PR depends on #18, merge that one first.

### CODE REVIEW

**Comment by forsaken1** [comment]
I will test it and merge tomorrow

**Comment by forsaken1** [comment]
sorry, I have a lot of work, I will fix conflicts and check PR at Sunday

**Comment by forsaken1** [comment]
@Wowu https://rubygems.org/gems/activeadmin_latlng 1.3.0

**Comment by Wowu** [comment]
Great, thanks 😄

**Pull request merged**
